# Generated by Django 5.0.6 on 2024-06-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookphoto',
            options={'verbose_name': 'Book Photo', 'verbose_name_plural': 'Book Photos'},
        ),
        migrations.AlterField(
            model_name='bookphoto',
            name='img',
            field=models.ImageField(upload_to='book_photos/%Y/%m/%d/'),
        ),
    ]
